// <auto-generated />
using System;
using CampusCinema.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CampusCinema.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260620115226_AddHallTable")]
    partial class AddHallTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CampusCinema.Api.Models.Hall", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ColumnCount")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RowCount")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Halls");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ColumnCount = 8,
                            Name = "校园一号厅",
                            RowCount = 5,
                            Status = "启用",
                            Type = "普通厅"
                        },
                        new
                        {
                            Id = 2,
                            ColumnCount = 12,
                            Name = "校园报告厅",
                            RowCount = 8,
                            Status = "启用",
                            Type = "报告厅"
                        });
                });

            modelBuilder.Entity("CampusCinema.Api.Models.Movie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Actors")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Director")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Duration")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PosterUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ReleaseDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Score")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Movies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Actors = "吴京、刘德华、李雪健",
                            Category = "科幻",
                            Description = "太阳即将毁灭，人类在地球表面建造出巨大的推进器，寻找新的家园。",
                            Director = "郭帆",
                            Duration = 173,
                            Name = "流浪地球2",
                            PosterUrl = "https://picsum.photos/300/420?random=1",
                            ReleaseDate = new DateTime(2023, 1, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Score = 8.3m,
                            Status = "正在热映"
                        },
                        new
                        {
                            Id = 2,
                            Actors = "沈腾、易烊千玺、张译",
                            Category = "悬疑",
                            Description = "南宋绍兴年间，一场围绕密信展开的悬疑故事。",
                            Director = "张艺谋",
                            Duration = 159,
                            Name = "满江红",
                            PosterUrl = "https://picsum.photos/300/420?random=2",
                            ReleaseDate = new DateTime(2023, 1, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Score = 7.0m,
                            Status = "正在热映"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
